.PHONY: install pull

install:
	mkdir -p ~/.config/Code/User
	cp settings.json ~/.config/Code/User/settings.json
	cp keybindings.json ~/.config/Code/User/keybindings.json 

pull:
	cp ~/.config/Code/User/settings.json settings.json
	cp ~/.config/Code/User/keybindings.json keybindings.json